const DATA_URL='/portfolio-data.json';
const labels={social:'Social Media',branding:'Brand Identity',packaging:'Packaging',web:'Web & UI',print:'Print & Editorial',church:'Church & Ministry',other:'Other'};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let rows=[],groups=[];
function normalize(data){return (data.projects||[]).slice().sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999)).map(p=>({...p,items:(p.images||[]).map((image,i)=>({title:p.title,image_path:image,sort_order:i}))}))}
function imageUrl(item){return '/'+String(item.image_path||'').replace(/^\/+/, '')}
function render(filter='all'){
 const root=document.getElementById('projects');
 const set=groups.filter(g=>filter==='all'||g.category===filter).slice(0,8);
 if(!set.length){root.innerHTML='<div class="empty">No selected projects in this category yet.</div>';return}
 root.innerHTML='';
 set.forEach(g=>{const p=g.items[0],card=document.createElement('article');card.className='case-card';card.innerHTML=`<img loading="lazy" src="${esc(imageUrl(p))}" alt="${esc(g.title)}" onerror="this.closest('.case-card').classList.add('asset-pending');this.style.display='none'"><div class="case-info"><div class="case-cat mono">${esc(g.categoryLabel||labels[g.category]||g.category)}</div><div class="case-title">${esc(g.title)}</div><div class="case-summary">${esc(g.summary||'A selected portfolio project.')}</div><span class="case-count">${g.items.length} ${g.items.length===1?'piece':'related pieces'} · View story ↗</span></div>`;card.onclick=()=>openStory(g);root.appendChild(card)})
}
function openStory(g){document.getElementById('story-cat').textContent=g.categoryLabel||labels[g.category]||g.category;document.getElementById('story-title').textContent=g.title;document.getElementById('story-text').textContent=g.summary||'A curated visual project.';document.getElementById('story-deliverables').textContent=g.deliverables||g.categoryLabel||'Visual Design';document.getElementById('story-count').textContent=`${g.items.length} related ${g.items.length===1?'piece':'pieces'}`;document.getElementById('story-gallery').innerHTML=g.items.map(p=>`<img loading="lazy" src="${esc(imageUrl(p))}" alt="${esc(p.title||g.title)}">`).join('');openModal('case-modal')}
function openModal(id){document.getElementById(id).classList.add('open');document.body.classList.add('lock')}
function closeModal(id){document.getElementById(id).classList.remove('open');document.body.classList.remove('lock')}
async function boot(){try{const res=await fetch(DATA_URL,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();groups=normalize(data);rows=groups.flatMap(g=>g.items.map(i=>({...i,category:g.category,categoryLabel:g.categoryLabel,title:g.title})));render();if(data.siteContent?.contactEmail){const e=document.getElementById('email-btn');e.href=`mailto:${data.siteContent.contactEmail}`;const a=document.createElement('a');a.href=e.href;a.textContent='Email';document.getElementById('contact-links')?.prepend(a)}const ts=data.siteContent?.testimonials||[];const tr=document.getElementById('testimonials');if(tr)tr.innerHTML=ts.length?ts.slice(0,6).map(t=>`<article class="quote"><div><div class="quote-mark">“</div><p>${esc(t.quote)}</p></div><small>${esc(t.brandName||'Client')}${t.brandRole?' · '+esc(t.brandRole):''}</small></article>`).join(''):'<div class="empty">Client feedback will appear here as it is added.</div>'}catch(err){console.error(err);document.getElementById('projects').innerHTML='<div class="empty">Portfolio data could not load.</div>'}}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});const all=document.getElementById('all-work-btn');if(all)all.onclick=()=>{document.getElementById('all-grid').innerHTML=rows.map(p=>`<div class="all-item"><img loading="lazy" src="${esc(imageUrl(p))}" alt="${esc(p.title||'Portfolio work')}"><div class="all-label">${esc(p.title||'Untitled')} · ${esc(p.categoryLabel||labels[p.category]||'Design')}</div></div>`).join('');openModal('all-modal')};document.getElementById('year').textContent=new Date().getFullYear();boot();
