/* Progressive enhancement: navigation, work and contact remain usable without JS. */
const API='https://wwuutndlekinlkdgjyao.supabase.co';
const KEY='sb_publishable_JxpzvFGpaX83HsVJfweM4A__Fi4jY24';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const patterns={'wingate-exotic-hotel':/wingate/i,'foot-impact':/foot[\s_-]*impact/i,'yellow-yolk-feeds':/yellow[\s_-]*yolk/i,'sparkles-packaging':/sparkles/i};
const usable=p=>p.image_path&&!/^(untitled(?: project)?(?: \d+)?|project title|another project)$/i.test((p.title||'').trim());
const source=p=>API+'/storage/v1/object/public/zayon-media/'+String(p.image_path).split('/').map(encodeURIComponent).join('/');
async function getJSON(url,headers={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),6000);try{const r=await fetch(url,{headers,signal:controller.signal});if(!r.ok)throw new Error('Unavailable');return await r.json()}finally{clearTimeout(timer)}}
async function collection(){try{return (await getJSON(API+'/rest/v1/portfolio_projects?select=title,category,image_path,sort_order&order=sort_order.asc',{apikey:KEY})).filter(usable)}catch{try{return await getJSON('/archive-data.json')}catch{return []}}}
function figure(p){const f=document.createElement('figure');const a=document.createElement('a');a.href=source(p);a.target='_blank';a.rel='noopener';a.setAttribute('aria-label','Open '+p.title+' image in a new tab');const im=document.createElement('img');im.src=a.href;im.alt=p.title;im.loading='lazy';im.addEventListener('error',()=>f.remove());a.append(im);const caption=document.createElement('figcaption');caption.textContent=p.title;f.append(a,caption);return f}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});let count=0;document.querySelectorAll('#selected-grid [data-category]').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter;if(!card.hidden)count++});document.getElementById('filter-status').textContent=count+(count===1?' project shown':' projects shown');}));
document.getElementById('print-profile')?.addEventListener('click',()=>window.print());
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const menu=document.querySelector('.mobile-nav');if(menu?.open){menu.open=false;menu.querySelector('summary').focus()}}});
const additional=document.querySelector('[data-project]');
if(additional){additional.hidden=true;collection().then(rows=>{const set=rows.filter(p=>patterns[additional.dataset.project]?.test(p.title));if(set.length){const root=additional.querySelector('[data-gallery]');set.forEach(p=>root.append(figure(p)));additional.querySelector('.collection-status').remove();additional.hidden=false}})}
const archive=document.getElementById('archive-grid');
if(archive){collection().then(rows=>{const status=document.getElementById('archive-status');if(!rows.length){status.textContent='Explore the selected projects below.';return}const group=new Map();rows.forEach(p=>{const key=Object.keys(patterns).find(k=>patterns[k].test(p.title))||p.category||'other';if(!group.has(key))group.set(key,[]);group.get(key).push(p)});const labels={'wingate-exotic-hotel':'Wingate Exotic Hotel','foot-impact':'Foot Impact','sparkles-packaging':'Sparkles Packaging',social:'Campaigns',branding:'Identity',packaging:'Packaging',web:'Web',print:'Print',church:'Church & ministry',other:'Other work'};const container=document.createElement('div');for(const [key,items] of group){const section=document.createElement('section');const heading=document.createElement('h2');heading.textContent=labels[key]||key;section.append(heading);if(patterns[key]){const link=document.createElement('a');link.href='/projects/'+key;link.textContent='Read the project story ↗';section.append(link)}const grid=document.createElement('div');grid.className='project-gallery archive-gallery';items.forEach(p=>grid.append(figure(p)));section.append(grid);container.append(section)}archive.replaceWith(container);status.textContent='Browse additional artwork by project and discipline. Select an image to view it at full size.'})}
const contact=document.getElementById('contact-action');
if(contact){getJSON(API+'/rest/v1/site_content?select=contact_email&id=eq.1',{apikey:KEY}).then(rows=>{const email=rows[0]?.contact_email;if(typeof email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){const a=document.createElement('a');a.className='btn primary';a.href='mailto:'+email;a.textContent='Email me ↗';contact.before(a)}}).catch(()=>{})}
